### ISSUE TITLE
How to label new generated person images?

### ISSUE THREAD

**Issue by GuangxingHan** [jpainam/SLS_ReID#1]
After reading the paper, I'm still confused about this problem. Could you explain it more clearly?

**Comment by jpainam** [comment]
![regularization](https://user-images.githubusercontent.com/1701705/45926225-da919e80-bf52-11e8-93ab-1aeb2a899fe9.PNG)
A generated image is assigned a smooth label according to its cluster or origin. An update to include such illustration is coming soon. The loss function follows [this ](https://arxiv.org/abs/1701.07717) implementation

**Comment by GuangxingHan** [comment]
@jpainam Ok, got it, thank you!
