### ISSUE TITLE
There is no viper_softmax_pretrain.h5

### ISSUE THREAD

**Issue by huangyuyu0426** [jpainam/SLS_ReID#2]
In clustering.py,the checkpoint does not exist.

**Comment by mittlin** [comment]
@huangyuyu0426 @jpainam  any ideas about this file ??

**Comment by jpainam** [comment]
@mittlin sorry for the late reply. You can download the pre-trained model used in my work [here](https://drive.google.com/drive/folders/1rC1k6LXC9sKeUFCwU6b0jwWSQegQpKlC?usp=sharing) . According to the dataset, make sure you change the CHECKPOINT at https://github.com/jpainam/SLS_ReID/blob/4be649c81bcb231d38993dfe33ac8d11ebd3313b/clustering/clustering.py#L33 with the correct checkpoint.
