### ISSUE TITLE
The code about cluster

### ISSUE THREAD

**Issue by youmizai** [jpainam/SLS_ReID#4]
Hello, thank you very much for the code you provided. When I was getting the GAN to generate the data, but I didn't see the pre-trained code before the cluster. Can you upload the relevant code to the website?

**Comment by jpainam** [comment]
I, sorry, i didn't share the code. it was just a resnet50 model where the last fully connected layer was changed to match the number of classes for each dataset. You can find the pretrained model [here](https://drive.google.com/drive/folders/1rC1k6LXC9sKeUFCwU6b0jwWSQegQpKlC?usp=sharing) and the model design in clustering.py (build in Keras)
